spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pro_cloud?useSSL=false&useUnicode=yes&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: zl
    password: zl123


