server:
  port: 7000
  servlet:
    context-path: /security

spring:
  application:
    name: @artifactId@
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/SpringSecurity?useSSL=true&useUnicode=yes&characterEncoding=UTF8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: ENC(1SWsO16NEBWAZ0x39O4DRQ==)
    password: ENC(zzz9lC/zkYjpu3uGZYZkUA==)
  redis:
    host: 127.0.0.1
    port: 6379
    password:

#  security:
#    user:
#      name: ENC(1SWsO16NEBWAZ0x39O4DRQ==)
#      password: ENC(zzz9lC/zkYjpu3uGZYZkUA==)

mybatis:
  mapper-locations: classpath:mybatis/*.*xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.example.security.domain



#加密和解密需要的salt
jasypt:
  encryptor:
    password: ${spring.application.name}




